[project]
authors = ["Mootfrost777 <andrey13102007@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "brick-ai"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.5.2,<2"
modal = ">=0.4.1,<0.5"
tqdm = ">=4.67.0,<5"
imgaug = ">=0.4.0,<0.5"
opencv = ">=4.10.0,<5"
tk = ">=8.6.13,<9"
pillow = ">=11.0.0,<12"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
pyserial = ">=3.5,<4"




